export const ADD_CART_ITEM ='ADD_CART_ITEM'
export const REMOVE_CART_ITEM ='REMOVE_CART_ITEM'


export const SAVE_SHIPPING_ADDRESS ='SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD ='SAVE_PAYMENT_METHOD'
