export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const ORDER_DETAILS_REQUEST =  'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS =  'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILURE =  'ORDER_DETAILS_FAILURE'

export const ORDER_PAY_REQUEST =  'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS =  'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE =  'ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET =  'ORDER_PAY_RESET'

export const ORDER_DELIVER_REQUEST =  'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS =  'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAILURE =  'ORDER_DELIVER_FAILURE'
export const ORDER_DELIVER_RESET =  'ORDER_DELIVER_RESET'


export const LIST_MY_ORDER_REQUEST =  'LIST_MY_ORDER_REQUEST'
export const LIST_MY_ORDER_SUCCESS =  'LIST_MY_ORDER_SUCCESS'
export const LIST_MY_ORDER_FAILURE =  'LIST_MY_ORDER_FAILURE'

export const ORDER_LIST_REQUEST =  'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS =  'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE =  'ORDER_LIST_FAILURE'